// Kennion buyer pipeline — seeded from the 4/30/26 buyer list
// Stages: outreach → nda → chemistry → loi → closed (or passed)

export const STAGES = [
  { id: "outreach",  label: "Outreach",     short: "OUT" },
  { id: "nda",       label: "NDA Signed",   short: "NDA" },
  { id: "chemistry", label: "Chemistry",    short: "CHM" },
  { id: "loi",       label: "LOI Received", short: "LOI" },
  { id: "closed",    label: "Closed",       short: "CLS" },
];

export const STAGE_INDEX = Object.fromEntries(STAGES.map((s, i) => [s.id, i]));

export const PROCESS_TASKS = [
  { id: "data",        label: "Gather Data",                    phase: "Preparation",        weeksFromStart: 0 },
  { id: "proforma",    label: "Pro Forma & Model",              phase: "Preparation",        weeksFromStart: 2 },
  { id: "cim_draft",   label: "Draft CIM",                      phase: "Preparation",        weeksFromStart: 3 },
  { id: "cim_final",   label: "Finalize CIM / Materials",       phase: "Preparation",        weeksFromStart: 4 },
  { id: "outreach",    label: "Reach out to Buyers / NDAs",     phase: "Marketing Phase 1",  weeksFromStart: 5 },
  { id: "cim_deliver", label: "Deliver CIM",                    phase: "Marketing Phase 1",  weeksFromStart: 6 },
  { id: "qa",          label: "Q&A Calls with Reagan",          phase: "Marketing Phase 2",  weeksFromStart: 8 },
  { id: "chemistry",   label: "Chemistry Meetings",             phase: "Marketing Phase 2",  weeksFromStart: 9 },
  { id: "lois",        label: "Receive Letters of Intent",      phase: "Marketing Phase 2",  weeksFromStart: 12 },
  { id: "select",      label: "Select Final Buyer",             phase: "Exclusivity",        weeksFromStart: 14 },
  { id: "loi_exec",    label: "Negotiate & Execute LOI",        phase: "Exclusivity",        weeksFromStart: 15 },
  { id: "diligence",   label: "Confirmatory Diligence / Legal", phase: "Exclusivity",        weeksFromStart: 17 },
  { id: "close",       label: "Closing and Funding",            phase: "Close",              weeksFromStart: 22 },
];

export const PHASES = ["Preparation", "Marketing Phase 1", "Marketing Phase 2", "Exclusivity", "Close"];

export const PROCESS_DEFAULT = {
  currentTaskId: "cim_final",
  currentTaskDate: "2026-04-30",
};

// Buyer roster — structural profile facts only (name, sponsor, stage, dates,
// flags). Opinion fields (notes, thesis, fit, probability) are intentionally
// stripped here so the AI rescan generates them from market comps + precedents
// on first run. The "Reset to clean slate" tweak rewinds live state to this
// shape too. Historical opinion seed values from earlier iterations were
// removed in this commit; refer to git history if you need them back.
const _RAW_BUYERS = [
  {
    id: "hub",
    rank: 1,
    name: "Hub International",
    website: "https://www.hubinternational.com",
    hq: "Chicago, IL",
    revenue: "$4.8B",
    headcount: "20,000",
    offices: "570+",
    ownership: "PE-backed",
    sponsor: "H&F",
    sources: {
      ownership: {
        kind: 'manual',
        label: 'Sponsor name from Reagan list 4/30/26',
        note: 'Source URL pending — verify against sponsor press release or Pitchbook profile',
      },
    },
    type: "National consolidator",
    stage: "nda",
    nda_signed: "2026-05-04",
    notes: "Top-tier consolidator. Reagan flagged as likely top-3 bidder. Aggressive integration playbook.",
    flags: [],
    fit: { size: 5, benefits: 3, pe: 1, precedent: 5 },
    thesis: "Scale buyer with active 2025-26 M&A cadence. Capacity to absorb a benefits-heavy book and pay for it. Risk: integration discount on cultural fit.",
    probability: 22,
  },
  {
    id: "alliant",
    rank: 2,
    name: "Alliant",
    website: "https://www.alliant.com",
    hq: "Irvine, CA",
    revenue: "$4.2B",
    headcount: "14,000+",
    offices: "100+",
    ownership: "PE-backed",
    sponsor: "Stone Point",
    sources: {
      ownership: {
        kind: 'manual',
        label: 'Sponsor name from Reagan list 4/30/26',
        note: 'Source URL pending — verify against sponsor press release or Pitchbook profile',
      },
    },
    type: "Diversified broker",
    stage: "nda",
    nda_signed: "2026-05-06",
    notes: "Diversified, less benefits-centric. Stone Point recently recapitalized. Could surprise on price; strategic fit weaker.",
    flags: ["Less benefits-heavy"],
    fit: { size: 5, benefits: 2, pe: 1, precedent: 4 },
    thesis: "Deep capital base; benefits not the priority vertical. Watch as financial bidder more than strategic.",
    probability: 14,
  },
  {
    id: "baldwin",
    rank: 3,
    name: "Baldwin Group / CAC",
    website: "https://www.baldwin.com",
    hq: "Tampa, FL",
    revenue: "$1.5B",
    headcount: "5,020",
    offices: "Public (BWIN)",
    ownership: "Public",
    sponsor: "—",
    type: "Public consolidator",
    stage: "outreach",
    notes: "Hunter add. CAC = Cobbs Allen, Birmingham roots. Bobby flagged BWIN stock pressure may limit M&A appetite this cycle.",
    flags: ["Stock pressure", "M&A appetite uncertain"],
    fit: { size: 4, benefits: 3, pe: 0, precedent: 3 },
    thesis: "Strategic + cultural overlap via CAC, but capital-markets headwinds make a competitive bid harder.",
    probability: 9,
  },
  {
    id: "cb",
    rank: 4,
    name: "Cottingham & Butler",
    website: "https://www.cottinghambutler.com",
    hq: "Dubuque, IA",
    revenue: "$1.2B",
    headcount: "1,300+",
    offices: "35",
    ownership: "Private (no PE)",
    sponsor: "—",
    type: "Captive specialist",
    stage: "nda",
    nda_signed: "2026-05-05",
    notes: "Private, no PE. Captive specialist — direct strategic fit. Slower decision cycle but high conviction when they move.",
    flags: [],
    fit: { size: 4, benefits: 5, pe: 0, precedent: 4 },
    thesis: "Strongest pure-strategic fit on the list. Captive expertise overlaps directly with our book. Less price tension than PE bidders.",
    probability: 18,
  },
  {
    id: "onedigital",
    rank: 5,
    name: "OneDigital",
    website: "https://www.onedigital.com",
    hq: "Atlanta, GA",
    revenue: "$870M",
    headcount: "3,200-3,500",
    offices: "125",
    ownership: "PE-backed",
    sponsor: "Onex / New Mountain",
    sources: {
      ownership: {
        kind: 'manual',
        label: 'Sponsor name from Reagan list 4/30/26',
        note: 'Source URL pending — verify against sponsor press release or Pitchbook profile',
      },
    },
    type: "Pure benefits",
    stage: "chemistry",
    nda_signed: "2026-05-02",
    chemistry_date: "2026-05-22",
    notes: "Atlanta-based, pure benefits. Best targeted distribution match. New Mountain co-sponsor. Expect aggressive process engagement.",
    flags: [],
    fit: { size: 4, benefits: 5, pe: 1, precedent: 5 },
    thesis: "Highest distribution-fit. Pure benefits thesis aligns 1:1. PE sponsors actively deploying.",
    probability: 27,
  },
  {
    id: "ima",
    rank: 6,
    name: "IMA Financial Group",
    website: "https://www.imacorp.com",
    hq: "Denver, CO",
    revenue: "~$750M",
    headcount: "3,000",
    offices: "Multiple",
    ownership: "PE-backed",
    sponsor: "New Mountain",
    sources: {
      ownership: {
        kind: 'manual',
        label: 'Sponsor name from Reagan list 4/30/26',
        note: 'Source URL pending — verify against sponsor press release or Pitchbook profile',
      },
    },
    type: "Diversified broker",
    stage: "nda",
    nda_signed: "2026-05-07",
    notes: "Hunter add. Acquired Valent in Birmingham 10/1/25. 10 deals in 2025 — most active acquirer on the list.",
    flags: [],
    fit: { size: 4, benefits: 3, pe: 1, precedent: 5 },
    thesis: "Most active acquirer in 2025. Recent Birmingham proximity (Valent). Pattern says they bid; question is on price discipline.",
    probability: 16,
  },
  {
    id: "higgi",
    rank: 7,
    name: "Higginbotham",
    website: "https://www.higginbotham.com",
    hq: "Fort Worth, TX",
    revenue: "$750M",
    headcount: "3,000-4,000",
    offices: "140+",
    ownership: "PE-backed",
    sponsor: "Stone Point",
    sources: {
      ownership: {
        kind: 'manual',
        label: 'Sponsor name from Reagan list 4/30/26',
        note: 'Source URL pending — verify against sponsor press release or Pitchbook profile',
      },
    },
    type: "Mostly P&C",
    stage: "outreach",
    notes: "Hunter add. Mostly P&C. Declined twice informally — retry through formal Reagan process.",
    flags: ["Declined 2x informally"],
    fit: { size: 4, benefits: 2, pe: 1, precedent: 2 },
    thesis: "Two prior soft passes. Formal process may not change priors unless thesis has shifted internally.",
    probability: 5,
  },
  {
    id: "br",
    rank: 8,
    name: "Brown & Riding",
    website: "https://www.brownandriding.com",
    hq: "Sherman Oaks, CA",
    revenue: "~$300M",
    headcount: "400+",
    offices: "National",
    ownership: "Wholesale broker",
    sponsor: "—",
    type: "Top 10 wholesale",
    stage: "outreach",
    notes: "$2.5B premium placed. Wholesale orientation — Reagan thesis to confirm whether benefits acquisition fits.",
    flags: ["Thesis to confirm"],
    fit: { size: 3, benefits: 2, pe: 0, precedent: 2 },
    thesis: "Adjacent rather than core fit. Watch as outside chance.",
    probability: 4,
  },
  {
    id: "kelly",
    rank: 9,
    name: "Kelly Benefits",
    website: "https://www.kellybenefits.com",
    hq: "Sparks, MD",
    revenue: "$250M",
    headcount: "280",
    offices: "4",
    ownership: "Family-owned",
    sponsor: "—",
    type: "Mid-Atlantic regional",
    stage: "nda",
    nda_signed: "2026-05-09",
    notes: "Family-owned, no PE. Mid-Atlantic. Cultural-fit play. Smaller — would be a stretch financially.",
    flags: ["Size constraint"],
    fit: { size: 2, benefits: 5, pe: 0, precedent: 3 },
    thesis: "Cultural and product fit are real. Capacity to bid at market clears is the open question.",
    probability: 6,
  },
  {
    id: "cason",
    rank: 10,
    name: "The Cason Group",
    website: "https://www.thecasongroup.com/",
    hq: "Columbia, SC",
    revenue: "$168M",
    headcount: "~233",
    offices: "10",
    ownership: "PE-backed",
    sponsor: "Truelink",
    sources: {
      ownership: {
        kind: 'manual',
        label: 'Sponsor name from Reagan list 4/30/26',
        note: 'Source URL pending — verify against sponsor press release or Pitchbook profile',
      },
    },
    type: "Captive distributor",
    stage: "nda",
    nda_signed: "2026-05-08",
    notes: "PE-backed. Captive distributor through retail brokers. Direct product overlap — but capital base smaller than top tier.",
    flags: [],
    fit: { size: 2, benefits: 5, pe: 1, precedent: 3 },
    thesis: "High product overlap. Sponsor capacity to fund a stretch deal is the swing variable.",
    probability: 7,
  },
  {
    id: "oakbridge",
    rank: 11,
    name: "Oakbridge",
    website: "https://oakbridgeinsurance.com/",
    hq: "Atlanta, GA",
    revenue: "~$100-150M",
    headcount: "313",
    offices: "30",
    ownership: "PE-backed",
    sponsor: "—",
    sources: {
      ownership: {
        kind: 'manual',
        label: 'PE-backed per Reagan list 4/30/26',
        note: 'Sponsor not yet identified — confirm with Reagan',
      },
    },
    type: "Southeast regional",
    stage: "outreach",
    notes: "PE-backed Southeast regional. Limited national distribution. Local proximity to Atlanta.",
    flags: ["Limited national reach"],
    fit: { size: 2, benefits: 3, pe: 1, precedent: 2 },
    thesis: "Regional fit, limited capital. Realistic only as a tuck-in not a platform acquirer.",
    probability: 3,
  },
];

// Strip opinion/AI fields from each raw entry so the seed exported to the app
// starts truly clean. The first AI rescan generates fit, probability, thesis,
// market bands, and per-buyer reasoning from market comps + precedents.
const _OPINION_FIELDS = ['notes', 'thesis', 'probability', 'fit', 'noteLog', 'aiNotes', 'aiHistory', 'aiCitations', 'aiCitedPrecedents', 'aiConfidence', 'lastAnalyzed', 'multipleOverride'];
export const BUYERS = _RAW_BUYERS.map(b => {
  const clean = { ...b };
  for (const f of _OPINION_FIELDS) delete clean[f];
  return {
    ...clean,
    fit: { size: 0, benefits: 0, pe: 0, precedent: 0 },
    thesis: '',
    probability: 0,
    noteLog: [],
  };
});
